name: test

on: [push, pull_request_target]

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: install dependencies
              run: npm install
            - name: test
              run: npm test -- --coverage
            - name: upload coverage to Codecov
              uses: codecov/codecov-action@v2
